### ISSUE TITLE
Add prettier linting to github actions

### ISSUE THREAD

**Issue by cmgriffing** [cmgriffing/idiosyncrasy#13]

**Comment by Jonathan-Engel** [comment]
Ill take a crack at this one. Just started playing with actions/prettier recently, good learning opportunity!

**Comment by Jonathan-Engel** [comment]
@cmgriffing Do we want Prettier to run on git push or should I replace the linter already in main.yml? (Still new to this so I apologize if im barking up the wrong tree).

**Comment by Jonathan-Engel** [comment]
Not sure why the PR didn't get linked to this issue (i probably messed that up). 

https://github.com/cmgriffing/idiosyncrasy/pull/20

**Comment by cmgriffing** [comment]
Awesome work. Thanks.
