### ISSUE TITLE
Home: Getting Started (no animations yet)

### ISSUE THREAD

**Issue by cmgriffing** [cmgriffing/idiosyncrasy#15]
We need to scaffold the Getting Started section of the home page.

The fonts and colors should be available already.

Here is a link to the section of the Figma:

https://www.figma.com/file/6wg9cMORA4odapDwI6Ab1R/Untitled?node-id=528%3A1

Feel free to brainstorm animations, but lets try to keep them to a separate PR/Task afterwards.

**Comment by CodeItQuick** [comment]
Would like this issue, thanks griffing!

**Comment by cmgriffing** [comment]
closed by #16
