### ISSUE TITLE
Home: Extra Features

### ISSUE THREAD

**Issue by cmgriffing** [cmgriffing/idiosyncrasy#17]
https://www.figma.com/file/6wg9cMORA4odapDwI6Ab1R/Untitled?node-id=528%3A1

This is for the basic layout of this section. It should have all styling from the figma. You can ignore the slanted borders for now. That is being worked on elsewhere.

Create a self-contained component and put it on the home page.

**Comment by linuxuser07** [comment]
here

**Comment by cmgriffing** [comment]
Hey, just checking in. Is this still something you wanted to work on?
