### ISSUE TITLE
Contributor Signup

### ISSUE THREAD

**Issue by cmgriffing** [cmgriffing/idiosyncrasy#2]
If you would like to help contribute to this project, please comment on this issue so that I can tag you in the future on other issues and PRs.

**Comment by CodeSpent** [comment]
Signing up to contribute.

**Comment by Jonathan-Engel** [comment]
👋 Sign me up!

**Comment by cmgriffing** [comment]
Sorry for accidentally assigning here. I can't do so on the other issues but take a look at the Header ( #4 ) and Fonts ( #3 ) issues.

Comment on on that you want to do and I can then assign it.

**Comment by linuxuser07** [comment]
I can help with this
