### ISSUE TITLE
Home: Testimonials

### ISSUE THREAD

**Issue by cmgriffing** [cmgriffing/idiosyncrasy#22]
We need the yellow bar of quotes/testimonials.

Feel free to grab some lorem ipsum or movie quotes for placeholders. Put them in a json file somewhere for now. (possibly a 'data' folder in the src)

Make it so new quotes replace older quotes over time, one at a time.

Eventually we will try and animate the replacement, but for now simple replacement is fine.

https://www.figma.com/file/6wg9cMORA4odapDwI6Ab1R/Untitled?node-id=528%3A1

**Comment by alinsg** [comment]
I'll be working on it 🤞

**Comment by cmgriffing** [comment]
You mentioned you were busy a while back. Is this something you might still have time for at some point?
