### ISSUE TITLE
Home: Features

### ISSUE THREAD

**Issue by cmgriffing** [cmgriffing/idiosyncrasy#23]
See Figma for the design:

https://www.figma.com/file/6wg9cMORA4odapDwI6Ab1R/Untitled?node-id=528%3A1

Currently we just want to get the elements into the page.

Eventually in a separate PR we can think about animations or interactions with them. (click to expand? fade in out intersection observer? no plans yet.)

**Comment by CodeSpent** [comment]
I can take this on.
