### ISSUE TITLE
Add Fonts

### ISSUE THREAD

**Issue by cmgriffing** [cmgriffing/idiosyncrasy#3]
We need to add the Fonts to the page and style them generically within the app.

The Body and Header font is IBM Plex Sans
The Logo font is Poppins.
Both can be found at Google Fonts.

We need the link elements added to the header using Helmet.
This could be done in the Layout component.
https://github.com/nfl/react-helmet

We also need a "*" global declaration in the main styles.css to give the various text elements the styling they need.

**Comment by youugotssponged** [comment]
Ill take a stab at this
