### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by cmgriffing** [cmgriffing/idiosyncrasy#4]
We need the links and logo in the header.

All colors are available in the common/colors.js file.
The background has been added so already.

The Header already has the InnerWrapper but maybe take note of what its doing inside the layout.js file.

Fonts are part of another task.

See https://www.figma.com/file/6wg9cMORA4odapDwI6Ab1R/Untitled?node-id=528%3A1
for designs.

**Comment by CodeSpent** [comment]
I'll take on this issue.
